--
-- Generated at https://bwdmedia.net/resource/sql-generator-for-indian-cities/
--

INSERT INTO `cities` (`city_id`,`city_name`,`state_id`,`state_name`) VALUES 
(NULL,"Adilabad","32","Telangana"),
(NULL,"Agra","34","Uttar Pradesh"),
(NULL,"Ahmed Nagar","21","Maharashtra"),
(NULL,"Ahmedabad City","12","Gujarat"),
(NULL,"Aizawl","24","Mizoram"),
(NULL,"Ajmer","29","Rajasthan"),
(NULL,"Akola","21","Maharashtra"),
(NULL,"Aligarh","34","Uttar Pradesh"),
(NULL,"Allahabad","34","Uttar Pradesh"),
(NULL,"Alleppey","18","Kerala"),
(NULL,"Almora","35","Uttarakhand"),
(NULL,"Alwar","29","Rajasthan"),
(NULL,"Alwaye","18","Kerala"),
(NULL,"Amalapuram","2","Andhra Pradesh"),
(NULL,"Ambala","13","Haryana"),
(NULL,"Ambedkar Nagar","34","Uttar Pradesh"),
(NULL,"Amravati","21","Maharashtra"),
(NULL,"Amreli","12","Gujarat"),
(NULL,"Amritsar","28","Punjab"),
(NULL,"Anakapalle","2","Andhra Pradesh"),
(NULL,"Anand","12","Gujarat"),
(NULL,"Anantapur","2","Andhra Pradesh"),
(NULL,"Ananthnag","15","Jammu & Kashmir"),
(NULL,"Anna Road H.O","31","Tamil Nadu"),
(NULL,"Arakkonam","31","Tamil Nadu"),
(NULL,"Asansol","36","West Bengal"),
(NULL,"Aska","26","Odisha"),
(NULL,"Auraiya","34","Uttar Pradesh"),
(NULL,"Aurangabad","21","Maharashtra"),
(NULL,"Aurangabad(Bihar)","5","Bihar"),
(NULL,"Azamgarh","34","Uttar Pradesh"),
(NULL,"Bagalkot","17","Karnataka"),
(NULL,"Bageshwar","35","Uttarakhand"),
(NULL,"Bagpat","34","Uttar Pradesh"),
(NULL,"Bahraich","34","Uttar Pradesh"),
(NULL,"Balaghat","20","Madhya Pradesh"),
(NULL,"Balangir","26","Odisha"),
(NULL,"Balasore","26","Odisha"),
(NULL,"Ballia","34","Uttar Pradesh"),
(NULL,"Balrampur","34","Uttar Pradesh"),
(NULL,"Banasanktha","12","Gujarat"),
(NULL,"Banda","34","Uttar Pradesh"),
(NULL,"Bandipur","15","Jammu & Kashmir"),
(NULL,"Bankura","36","West Bengal"),
(NULL,"Banswara","29","Rajasthan"),
(NULL,"Barabanki","34","Uttar Pradesh"),
(NULL,"Baramulla","15","Jammu & Kashmir"),
(NULL,"Baran","29","Rajasthan"),
(NULL,"Bardoli","12","Gujarat"),
(NULL,"Bareilly","34","Uttar Pradesh"),
(NULL,"Barmer","29","Rajasthan"),
(NULL,"Barnala","28","Punjab"),
(NULL,"Barpeta","4","Assam"),
(NULL,"Bastar","7","Chattisgarh"),
(NULL,"Basti","34","Uttar Pradesh"),
(NULL,"Bathinda","28","Punjab"),
(NULL,"Beed","21","Maharashtra"),
(NULL,"Begusarai","5","Bihar"),
(NULL,"Belgaum","17","Karnataka"),
(NULL,"Bellary","17","Karnataka"),
(NULL,"Bengaluru East","17","Karnataka"),
(NULL,"Bengaluru South","17","Karnataka"),
(NULL,"Bengaluru West","17","Karnataka"),
(NULL,"Berhampur","26","Odisha"),
(NULL,"Bhadrak","26","Odisha"),
(NULL,"Bhagalpur","5","Bihar"),
(NULL,"Bhandara","21","Maharashtra"),
(NULL,"Bharatpur","29","Rajasthan"),
(NULL,"Bharuch","12","Gujarat"),
(NULL,"Bhavnagar","12","Gujarat"),
(NULL,"Bhilwara","29","Rajasthan"),
(NULL,"Bhimavaram","2","Andhra Pradesh"),
(NULL,"Bhiwani","13","Haryana"),
(NULL,"Bhojpur","5","Bihar"),
(NULL,"Bhopal","20","Madhya Pradesh"),
(NULL,"Bhubaneswar","26","Odisha"),
(NULL,"Bidar","17","Karnataka"),
(NULL,"Bijapur","17","Karnataka"),
(NULL,"Bijnor","34","Uttar Pradesh"),
(NULL,"Bikaner","29","Rajasthan"),
(NULL,"Bilaspur","7","Chattisgarh"),
(NULL,"Birbhum","36","West Bengal"),
(NULL,"Bishnupur","22","Manipur"),
(NULL,"Bongaigaon","4","Assam"),
(NULL,"Budaun","34","Uttar Pradesh"),
(NULL,"Budgam","15","Jammu & Kashmir"),
(NULL,"Bulandshahr","34","Uttar Pradesh"),
(NULL,"Buldhana","21","Maharashtra"),
(NULL,"Bundi","29","Rajasthan"),
(NULL,"Burdwan","36","West Bengal"),
(NULL,"Cachar","4","Assam"),
(NULL,"Calicut","18","Kerala"),
(NULL,"Carnicobar","1","Andaman & Nicobar Islands"),
(NULL,"Chamba","14","Himachal Pradesh"),
(NULL,"Chamoli","35","Uttarakhand"),
(NULL,"Champawat","35","Uttarakhand"),
(NULL,"Champhai","24","Mizoram"),
(NULL,"Chandauli","34","Uttar Pradesh"),
(NULL,"Chandel","22","Manipur"),
(NULL,"Chandigarh","6","Chandigarh"),
(NULL,"Chandrapur","21","Maharashtra"),
(NULL,"Changanacherry","18","Kerala"),
(NULL,"Changlang","3","Arunachal Pradesh"),
(NULL,"Channapatna","17","Karnataka"),
(NULL,"Chengalpattu","31","Tamil Nadu"),
(NULL,"Chennai City Central","31","Tamil Nadu"),
(NULL,"Chennai City North","31","Tamil Nadu"),
(NULL,"Chennai City South","31","Tamil Nadu"),
(NULL,"Chhatarpur","20","Madhya Pradesh"),
(NULL,"Chhindwara","20","Madhya Pradesh"),
(NULL,"Chikmagalur","17","Karnataka"),
(NULL,"Chikodi","17","Karnataka"),
(NULL,"Chitradurga","17","Karnataka"),
(NULL,"Chitrakoot","34","Uttar Pradesh"),
(NULL,"Chittoor","2","Andhra Pradesh"),
(NULL,"Chittorgarh","29","Rajasthan"),
(NULL,"Churachandpur","22","Manipur"),
(NULL,"Churu","29","Rajasthan"),
(NULL,"Coimbatore","31","Tamil Nadu"),
(NULL,"Contai","36","West Bengal"),
(NULL,"Cooch Behar","36","West Bengal"),
(NULL,"Cuddalore","31","Tamil Nadu"),
(NULL,"Cuddapah","2","Andhra Pradesh"),
(NULL,"Cuttack City","26","Odisha"),
(NULL,"Cuttack North","26","Odisha"),
(NULL,"Cuttack South","26","Odisha"),
(NULL,"Dadra & Nagar Haveli","8","Dadra & Nagar Haveli"),
(NULL,"Daman","9","Daman & Diu"),
(NULL,"Darbhanga","5","Bihar"),
(NULL,"Darjiling","36","West Bengal"),
(NULL,"Darrang","4","Assam"),
(NULL,"Dausa","29","Rajasthan"),
(NULL,"Dehra Gopipur","14","Himachal Pradesh"),
(NULL,"Dehradun","35","Uttarakhand"),
(NULL,"Delhi","10","Delhi"),
(NULL,"Deoria","34","Uttar Pradesh"),
(NULL,"Dhalai","33","Tripura"),
(NULL,"Dhanbad","16","Jharkhand"),
(NULL,"Dharamsala","14","Himachal Pradesh"),
(NULL,"Dharmapuri","31","Tamil Nadu"),
(NULL,"Dharwad","17","Karnataka"),
(NULL,"Dhemaji","4","Assam"),
(NULL,"Dhenkanal","26","Odisha"),
(NULL,"Dholpur","29","Rajasthan"),
(NULL,"Dhubri","4","Assam"),
(NULL,"Dhule","21","Maharashtra"),
(NULL,"Dibang Valley","3","Arunachal Pradesh"),
(NULL,"Dibrugarh","4","Assam"),
(NULL,"Diglipur","1","Andaman & Nicobar Islands"),
(NULL,"Dimapur","25","Nagaland"),
(NULL,"Dindigul","31","Tamil Nadu"),
(NULL,"Diu","9","Daman & Diu"),
(NULL,"Doda","15","Jammu & Kashmir"),
(NULL,"Dungarpur","29","Rajasthan"),
(NULL,"Durg","7","Chattisgarh"),
(NULL,"East Champaran","5","Bihar"),
(NULL,"East Garo Hills","23","Meghalaya"),
(NULL,"East Kameng","3","Arunachal Pradesh"),
(NULL,"East Khasi Hills","23","Meghalaya"),
(NULL,"East Siang","3","Arunachal Pradesh"),
(NULL,"East Sikkim","30","Sikkim"),
(NULL,"Eluru","2","Andhra Pradesh"),
(NULL,"Ernakulam","18","Kerala"),
(NULL,"Erode","31","Tamil Nadu"),
(NULL,"Etah","34","Uttar Pradesh"),
(NULL,"Etawah","34","Uttar Pradesh"),
(NULL,"Faizabad","34","Uttar Pradesh"),
(NULL,"Faridabad","13","Haryana"),
(NULL,"Faridkot","28","Punjab"),
(NULL,"Farrukhabad","34","Uttar Pradesh"),
(NULL,"Fatehgarh Sahib","28","Punjab"),
(NULL,"Fatehpur","34","Uttar Pradesh"),
(NULL,"Fazilka","28","Punjab"),
(NULL,"Ferrargunj","1","Andaman & Nicobar Islands"),
(NULL,"Firozabad","34","Uttar Pradesh"),
(NULL,"Firozpur","28","Punjab"),
(NULL,"Gadag","17","Karnataka"),
(NULL,"Gadchiroli","21","Maharashtra"),
(NULL,"Gandhinagar","12","Gujarat"),
(NULL,"Ganganagar","29","Rajasthan"),
(NULL,"Gautam Buddha Nagar","34","Uttar Pradesh"),
(NULL,"Gaya","5","Bihar"),
(NULL,"Ghaziabad","34","Uttar Pradesh"),
(NULL,"Ghazipur","34","Uttar Pradesh"),
(NULL,"Giridih","16","Jharkhand"),
(NULL,"Goa","11","Goa"),
(NULL,"Goalpara","4","Assam"),
(NULL,"Gokak","17","Karnataka"),
(NULL,"Golaghat","4","Assam"),
(NULL,"Gonda","34","Uttar Pradesh"),
(NULL,"Gondal","12","Gujarat"),
(NULL,"Gondia","21","Maharashtra"),
(NULL,"Gorakhpur","34","Uttar Pradesh"),
(NULL,"Gudivada","2","Andhra Pradesh"),
(NULL,"Gudur","2","Andhra Pradesh"),
(NULL,"Gulbarga","17","Karnataka"),
(NULL,"Guna","20","Madhya Pradesh"),
(NULL,"Guntur","2","Andhra Pradesh"),
(NULL,"Gurdaspur","28","Punjab"),
(NULL,"Gurugram","13","Haryana"),
(NULL,"Gwalior","20","Madhya Pradesh"),
(NULL,"Hailakandi","4","Assam"),
(NULL,"Hamirpur (HP)","14","Himachal Pradesh"),
(NULL,"Hamirpur (UP)","34","Uttar Pradesh"),
(NULL,"Hanamkonda","32","Telangana"),
(NULL,"Hanumangarh","29","Rajasthan"),
(NULL,"Hardoi","34","Uttar Pradesh"),
(NULL,"Haridwar","35","Uttarakhand"),
(NULL,"Hassan","17","Karnataka"),
(NULL,"Hathras","34","Uttar Pradesh"),
(NULL,"Haveri","17","Karnataka"),
(NULL,"Hazaribagh","16","Jharkhand"),
(NULL,"Hindupur","2","Andhra Pradesh"),
(NULL,"Hingoli","21","Maharashtra"),
(NULL,"Hissar","13","Haryana"),
(NULL,"Hooghly","36","West Bengal"),
(NULL,"Hoshangabad","20","Madhya Pradesh"),
(NULL,"Hoshiarpur","28","Punjab"),
(NULL,"Howrah","36","West Bengal"),
(NULL,"Hut Bay","1","Andaman & Nicobar Islands"),
(NULL,"Hyderabad City","32","Telangana"),
(NULL,"Hyderabad South East","32","Telangana"),
(NULL,"Idukki","18","Kerala"),
(NULL,"Imphal East","22","Manipur"),
(NULL,"Imphal West","22","Manipur"),
(NULL,"Indore City","20","Madhya Pradesh"),
(NULL,"Indore Moffusil","20","Madhya Pradesh"),
(NULL,"Irinjalakuda","18","Kerala"),
(NULL,"Jabalpur","20","Madhya Pradesh"),
(NULL,"Jaintia Hills","23","Meghalaya"),
(NULL,"Jaipur","29","Rajasthan"),
(NULL,"Jaisalmer","29","Rajasthan"),
(NULL,"Jalandhar","28","Punjab"),
(NULL,"Jalaun","34","Uttar Pradesh"),
(NULL,"Jalgaon","21","Maharashtra"),
(NULL,"Jalna","21","Maharashtra"),
(NULL,"Jalor","29","Rajasthan"),
(NULL,"Jalpaiguri","36","West Bengal"),
(NULL,"Jammu","15","Jammu & Kashmir"),
(NULL,"Jamnagar","12","Gujarat"),
(NULL,"Jaunpur","34","Uttar Pradesh"),
(NULL,"Jhalawar","29","Rajasthan"),
(NULL,"Jhansi","34","Uttar Pradesh"),
(NULL,"Jhujhunu","29","Rajasthan"),
(NULL,"Jodhpur","29","Rajasthan"),
(NULL,"Jorhat","4","Assam"),
(NULL,"Junagadh","12","Gujarat"),
(NULL,"Jyotiba Phule Nagar","34","Uttar Pradesh"),
(NULL,"Kakinada","2","Andhra Pradesh"),
(NULL,"Kalahandi","26","Odisha"),
(NULL,"Kamrup","4","Assam"),
(NULL,"Kanchipuram","31","Tamil Nadu"),
(NULL,"Kannauj","34","Uttar Pradesh"),
(NULL,"Kanniyakumari","31","Tamil Nadu"),
(NULL,"Kannur","18","Kerala"),
(NULL,"Kanpur Dehat","34","Uttar Pradesh"),
(NULL,"Kanpur Nagar","34","Uttar Pradesh"),
(NULL,"Kapurthala","28","Punjab"),
(NULL,"Karaikal","27","Poducherry"),
(NULL,"Karaikudi","31","Tamil Nadu"),
(NULL,"Karauli","29","Rajasthan"),
(NULL,"Karbi Anglong","4","Assam"),
(NULL,"Kargil","15","Jammu & Kashmir"),
(NULL,"Karimganj","4","Assam"),
(NULL,"Karimnagar","32","Telangana"),
(NULL,"Karnal","13","Haryana"),
(NULL,"Karur","31","Tamil Nadu"),
(NULL,"Karwar","17","Karnataka"),
(NULL,"Kasaragod","18","Kerala"),
(NULL,"Kathua","15","Jammu & Kashmir"),
(NULL,"Kaushambi","34","Uttar Pradesh"),
(NULL,"Keonjhar","26","Odisha"),
(NULL,"Khammam (AP)","2","Andhra Pradesh"),
(NULL,"Khammam (TL)","32","Telangana"),
(NULL,"Khandwa","20","Madhya Pradesh"),
(NULL,"Kheda","12","Gujarat"),
(NULL,"Kheri","34","Uttar Pradesh"),
(NULL,"Kiphire","25","Nagaland"),
(NULL,"Kodagu","17","Karnataka"),
(NULL,"Kohima","25","Nagaland"),
(NULL,"Kokrajhar","4","Assam"),
(NULL,"Kolar","17","Karnataka"),
(NULL,"Kolasib","24","Mizoram"),
(NULL,"Kolhapur","21","Maharashtra"),
(NULL,"Kolkata","36","West Bengal"),
(NULL,"Koraput","26","Odisha"),
(NULL,"Kota","29","Rajasthan"),
(NULL,"Kottayam","18","Kerala"),
(NULL,"Kovilpatti","31","Tamil Nadu"),
(NULL,"Krishnagiri","31","Tamil Nadu"),
(NULL,"Kulgam","15","Jammu & Kashmir"),
(NULL,"Kumbakonam","31","Tamil Nadu"),
(NULL,"Kupwara","15","Jammu & Kashmir"),
(NULL,"Kurnool","2","Andhra Pradesh"),
(NULL,"Kurukshetra","13","Haryana"),
(NULL,"Kurung Kumey","3","Arunachal Pradesh"),
(NULL,"Kushinagar","34","Uttar Pradesh"),
(NULL,"Kutch","12","Gujarat"),
(NULL,"Lakhimpur","4","Assam"),
(NULL,"Lakshadweep","19","Lakshadweep"),
(NULL,"Lalitpur","34","Uttar Pradesh"),
(NULL,"Latur","21","Maharashtra"),
(NULL,"Lawngtlai","24","Mizoram"),
(NULL,"Leh","15","Jammu & Kashmir"),
(NULL,"Lohit","3","Arunachal Pradesh"),
(NULL,"Longleng","25","Nagaland"),
(NULL,"Lower Subansiri","3","Arunachal Pradesh"),
(NULL,"Lucknow","34","Uttar Pradesh"),
(NULL,"Ludhiana","28","Punjab"),
(NULL,"Lunglei","24","Mizoram"),
(NULL,"Machilipatnam","2","Andhra Pradesh"),
(NULL,"Madhubani","5","Bihar"),
(NULL,"Madurai","31","Tamil Nadu"),
(NULL,"Mahabubnagar","32","Telangana"),
(NULL,"Maharajganj","34","Uttar Pradesh"),
(NULL,"Mahesana","12","Gujarat"),
(NULL,"Mahoba","34","Uttar Pradesh"),
(NULL,"Mainpuri","34","Uttar Pradesh"),
(NULL,"Malda","36","West Bengal"),
(NULL,"Mammit","24","Mizoram"),
(NULL,"Mandi","14","Himachal Pradesh"),
(NULL,"Mandsaur","20","Madhya Pradesh"),
(NULL,"Mandya","17","Karnataka"),
(NULL,"Mangalore","17","Karnataka"),
(NULL,"Manjeri","18","Kerala"),
(NULL,"Mansa","28","Punjab"),
(NULL,"Marigaon","4","Assam"),
(NULL,"Mathura","34","Uttar Pradesh"),
(NULL,"Mau","34","Uttar Pradesh"),
(NULL,"Mavelikara","18","Kerala"),
(NULL,"Mayabander","1","Andaman & Nicobar Islands"),
(NULL,"Mayiladuthurai","31","Tamil Nadu"),
(NULL,"Mayurbhanj","26","Odisha"),
(NULL,"Medak","32","Telangana"),
(NULL,"Meerut","34","Uttar Pradesh"),
(NULL,"Meghalaya","23","Meghalaya"),
(NULL,"Midnapore","36","West Bengal"),
(NULL,"Mirzapur","34","Uttar Pradesh"),
(NULL,"Moga","28","Punjab"),
(NULL,"Mohali","28","Punjab"),
(NULL,"Mokokchung","25","Nagaland"),
(NULL,"Mon","25","Nagaland"),
(NULL,"Monghyr","5","Bihar"),
(NULL,"Moradabad","34","Uttar Pradesh"),
(NULL,"Morena","20","Madhya Pradesh"),
(NULL,"Muktsar","28","Punjab"),
(NULL,"Mumbai","21","Maharashtra"),
(NULL,"Murshidabad","36","West Bengal"),
(NULL,"Muzaffarnagar","34","Uttar Pradesh"),
(NULL,"Muzaffarpur","5","Bihar"),
(NULL,"Mysore","17","Karnataka"),
(NULL,"Nadia","36","West Bengal"),
(NULL,"Nagaon","4","Assam"),
(NULL,"Nagapattinam","31","Tamil Nadu"),
(NULL,"Nagaur","29","Rajasthan"),
(NULL,"Nagpur","21","Maharashtra"),
(NULL,"Nainital","35","Uttarakhand"),
(NULL,"Nalanda","5","Bihar"),
(NULL,"Nalbari","4","Assam"),
(NULL,"Nalgonda","32","Telangana"),
(NULL,"Namakkal","31","Tamil Nadu"),
(NULL,"Nancorie","1","Andaman & Nicobar Islands"),
(NULL,"Nancowrie","1","Andaman & Nicobar Islands"),
(NULL,"Nanded","21","Maharashtra"),
(NULL,"Nandurbar","21","Maharashtra"),
(NULL,"Nandyal","2","Andhra Pradesh"),
(NULL,"Nanjangud","17","Karnataka"),
(NULL,"Narasaraopet","2","Andhra Pradesh"),
(NULL,"Nashik","21","Maharashtra"),
(NULL,"Navsari","12","Gujarat"),
(NULL,"Nawadha","5","Bihar"),
(NULL,"Nawanshahr","28","Punjab"),
(NULL,"Nellore","2","Andhra Pradesh"),
(NULL,"Nilgiris","31","Tamil Nadu"),
(NULL,"Nizamabad","32","Telangana"),
(NULL,"North 24 Parganas","36","West Bengal"),
(NULL,"North Cachar Hills","4","Assam"),
(NULL,"North Dinajpur","36","West Bengal"),
(NULL,"North Sikkim","30","Sikkim"),
(NULL,"North Tripura","33","Tripura"),
(NULL,"Osmanabad","21","Maharashtra"),
(NULL,"Ottapalam","18","Kerala"),
(NULL,"Palamau","16","Jharkhand"),
(NULL,"Palghat","18","Kerala"),
(NULL,"Pali","29","Rajasthan"),
(NULL,"Panchmahals","12","Gujarat"),
(NULL,"Papum Pare","3","Arunachal Pradesh"),
(NULL,"Parbhani","21","Maharashtra"),
(NULL,"Parvathipuram","2","Andhra Pradesh"),
(NULL,"Patan","12","Gujarat"),
(NULL,"Pathanamthitta","18","Kerala"),
(NULL,"Patiala","28","Punjab"),
(NULL,"Patna","5","Bihar"),
(NULL,"Pattukottai","31","Tamil Nadu"),
(NULL,"Pauri Garhwal","35","Uttarakhand"),
(NULL,"Peddapalli","32","Telangana"),
(NULL,"Peren","25","Nagaland"),
(NULL,"Phek","25","Nagaland"),
(NULL,"Phulbani","26","Odisha"),
(NULL,"Pilibhit","34","Uttar Pradesh"),
(NULL,"Pithoragarh","35","Uttarakhand"),
(NULL,"Poducherry (PD)","27","Poducherry"),
(NULL,"Poducherry (TN)","31","Tamil Nadu"),
(NULL,"Pollachi","31","Tamil Nadu"),
(NULL,"Poonch","15","Jammu & Kashmir"),
(NULL,"Porbandar","12","Gujarat"),
(NULL,"Port Blair","1","Andaman & Nicobar Islands"),
(NULL,"Prakasam","2","Andhra Pradesh"),
(NULL,"Pratapgarh","34","Uttar Pradesh"),
(NULL,"Proddatur","2","Andhra Pradesh"),
(NULL,"Pudukkottai","31","Tamil Nadu"),
(NULL,"Pulwama","15","Jammu & Kashmir"),
(NULL,"Pune","21","Maharashtra"),
(NULL,"Puri","26","Odisha"),
(NULL,"Purnea","5","Bihar"),
(NULL,"Purulia","36","West Bengal"),
(NULL,"Puttur","17","Karnataka"),
(NULL,"Quilon","18","Kerala"),
(NULL,"Raebareli","34","Uttar Pradesh"),
(NULL,"Raichur","17","Karnataka"),
(NULL,"Raigarh (CT)","7","Chattisgarh"),
(NULL,"Raigarh (MH)","21","Maharashtra"),
(NULL,"Raipur","7","Chattisgarh"),
(NULL,"Rajahmundry","2","Andhra Pradesh"),
(NULL,"Rajauri","15","Jammu & Kashmir"),
(NULL,"Rajkot","12","Gujarat"),
(NULL,"Rajsamand","29","Rajasthan"),
(NULL,"Ramanathapuram","31","Tamil Nadu"),
(NULL,"Rampur","34","Uttar Pradesh"),
(NULL,"Rampur Bushahr","14","Himachal Pradesh"),
(NULL,"Ranchi","16","Jharkhand"),
(NULL,"Rangat","1","Andaman & Nicobar Islands"),
(NULL,"Ratlam","20","Madhya Pradesh"),
(NULL,"Ratnagiri","21","Maharashtra"),
(NULL,"Reasi","15","Jammu & Kashmir"),
(NULL,"Rewa","20","Madhya Pradesh"),
(NULL,"Ri Bhoi","23","Meghalaya"),
(NULL,"Rohtak","13","Haryana"),
(NULL,"Rohtas","5","Bihar"),
(NULL,"Ropar","28","Punjab"),
(NULL,"Rudraprayag","35","Uttarakhand"),
(NULL,"Rupnagar","28","Punjab"),
(NULL,"Sabarkantha","12","Gujarat"),
(NULL,"Sagar","20","Madhya Pradesh"),
(NULL,"Saharanpur","34","Uttar Pradesh"),
(NULL,"Saharsa","5","Bihar"),
(NULL,"Salem East","31","Tamil Nadu"),
(NULL,"Salem West","31","Tamil Nadu"),
(NULL,"Samastipur","5","Bihar"),
(NULL,"Sambalpur","26","Odisha"),
(NULL,"Sangareddy","32","Telangana"),
(NULL,"Sangli","21","Maharashtra"),
(NULL,"Sangrur","28","Punjab"),
(NULL,"Sant Kabir Nagar","34","Uttar Pradesh"),
(NULL,"Sant Ravidas Nagar","34","Uttar Pradesh"),
(NULL,"Santhal Parganas","16","Jharkhand"),
(NULL,"Saran","5","Bihar"),
(NULL,"Satara","21","Maharashtra"),
(NULL,"Sawai Madhopur","29","Rajasthan"),
(NULL,"Secunderabad","32","Telangana"),
(NULL,"Sehore","20","Madhya Pradesh"),
(NULL,"Senapati","22","Manipur"),
(NULL,"Serchhip","24","Mizoram"),
(NULL,"Shahdol","20","Madhya Pradesh"),
(NULL,"Shahjahanpur","34","Uttar Pradesh"),
(NULL,"Shimla","14","Himachal Pradesh"),
(NULL,"Shimoga","17","Karnataka"),
(NULL,"Shrawasti","34","Uttar Pradesh"),
(NULL,"Sibsagar","4","Assam"),
(NULL,"Siddharthnagar","34","Uttar Pradesh"),
(NULL,"Sikar","29","Rajasthan"),
(NULL,"Sindhudurg","21","Maharashtra"),
(NULL,"Singhbhum","16","Jharkhand"),
(NULL,"Sirohi","29","Rajasthan"),
(NULL,"Sirsi","17","Karnataka"),
(NULL,"Sitamarhi","5","Bihar"),
(NULL,"Sitapur","34","Uttar Pradesh"),
(NULL,"Sivaganga","31","Tamil Nadu"),
(NULL,"Siwan","5","Bihar"),
(NULL,"Solan","14","Himachal Pradesh"),
(NULL,"Solapur","21","Maharashtra"),
(NULL,"Sonbhadra","34","Uttar Pradesh"),
(NULL,"Sonepat","13","Haryana"),
(NULL,"Sonitpur","4","Assam"),
(NULL,"South 24 Parganas","36","West Bengal"),
(NULL,"South Dinajpur","36","West Bengal"),
(NULL,"South Garo Hills","23","Meghalaya"),
(NULL,"South Sikkim","30","Sikkim"),
(NULL,"South Tripura","33","Tripura"),
(NULL,"Srikakulam","2","Andhra Pradesh"),
(NULL,"Srinagar","15","Jammu & Kashmir"),
(NULL,"Srirangam","31","Tamil Nadu"),
(NULL,"Sultanpur","34","Uttar Pradesh"),
(NULL,"Sundargarh","26","Odisha"),
(NULL,"Surat","12","Gujarat"),
(NULL,"Surendranagar","12","Gujarat"),
(NULL,"Suryapet","32","Telangana"),
(NULL,"Tadepalligudem","2","Andhra Pradesh"),
(NULL,"Tambaram","31","Tamil Nadu"),
(NULL,"Tamenglong","22","Manipur"),
(NULL,"Tamluk","36","West Bengal"),
(NULL,"Tarn Taran","28","Punjab"),
(NULL,"Tawang","3","Arunachal Pradesh"),
(NULL,"Tehri Garhwal","35","Uttarakhand"),
(NULL,"Tenali","2","Andhra Pradesh"),
(NULL,"Thalassery","18","Kerala"),
(NULL,"Thane","21","Maharashtra"),
(NULL,"Thanjavur","31","Tamil Nadu"),
(NULL,"Theni","31","Tamil Nadu"),
(NULL,"Thoubal","22","Manipur"),
(NULL,"Tinsukia","4","Assam"),
(NULL,"Tirap","3","Arunachal Pradesh"),
(NULL,"Tiruchirapalli","31","Tamil Nadu"),
(NULL,"Tirunelveli","31","Tamil Nadu"),
(NULL,"Tirupati","2","Andhra Pradesh"),
(NULL,"Tirupattur","31","Tamil Nadu"),
(NULL,"Tirupur","31","Tamil Nadu"),
(NULL,"Tirur","18","Kerala"),
(NULL,"Tiruvalla","18","Kerala"),
(NULL,"Tiruvannamalai","31","Tamil Nadu"),
(NULL,"Tonk","29","Rajasthan"),
(NULL,"Trichur","18","Kerala"),
(NULL,"Trivandrum North","18","Kerala"),
(NULL,"Trivandrum South","18","Kerala"),
(NULL,"Tuensang","25","Nagaland"),
(NULL,"Tumkur","17","Karnataka"),
(NULL,"Tuticorin","31","Tamil Nadu"),
(NULL,"Udaipur","29","Rajasthan"),
(NULL,"Udham Singh Nagar","35","Uttarakhand"),
(NULL,"Udhampur","15","Jammu & Kashmir"),
(NULL,"Udupi","17","Karnataka"),
(NULL,"Ujjain","20","Madhya Pradesh"),
(NULL,"Ukhrul","22","Manipur"),
(NULL,"Una","14","Himachal Pradesh"),
(NULL,"Unnao","34","Uttar Pradesh"),
(NULL,"Upper Siang","3","Arunachal Pradesh"),
(NULL,"Upper Subansiri","3","Arunachal Pradesh"),
(NULL,"Uttarkashi","35","Uttarakhand"),
(NULL,"Vadakara","18","Kerala"),
(NULL,"Vadodara East","12","Gujarat"),
(NULL,"Vadodara West","12","Gujarat"),
(NULL,"Vaishali","5","Bihar"),
(NULL,"Valsad","12","Gujarat"),
(NULL,"Varanasi","34","Uttar Pradesh"),
(NULL,"Vellore","31","Tamil Nadu"),
(NULL,"Vidisha","20","Madhya Pradesh"),
(NULL,"Vijayawada","2","Andhra Pradesh"),
(NULL,"Virudhunagar","31","Tamil Nadu"),
(NULL,"Visakhapatnam","2","Andhra Pradesh"),
(NULL,"Vizianagaram","2","Andhra Pradesh"),
(NULL,"Vriddhachalam","31","Tamil Nadu"),
(NULL,"Wanaparthy","32","Telangana"),
(NULL,"Warangal","32","Telangana"),
(NULL,"Wardha","21","Maharashtra"),
(NULL,"Washim","21","Maharashtra"),
(NULL,"West Champaran","5","Bihar"),
(NULL,"West Garo Hills","23","Meghalaya"),
(NULL,"West Kameng","3","Arunachal Pradesh"),
(NULL,"West Khasi Hills","23","Meghalaya"),
(NULL,"West Siang","3","Arunachal Pradesh"),
(NULL,"West Sikkim","30","Sikkim"),
(NULL,"West Tripura","33","Tripura"),
(NULL,"Wokha","25","Nagaland"),
(NULL,"Yavatmal","21","Maharashtra"),
(NULL,"Zunhebotto","25","Nagaland");